baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Página Pablo Lahoz'
theme = 'gokarna-hugo'

[menu]
  [[menu.main]]
    name = "Markdown"
    pre = "<span data-feather='book'></span>"
    url = "/markdown/"
    weight = 1

  [[menu.main]]
    name = "Carrousel Imágenes"
    pre = "<span data-feather='image'></span>"
    url = "galeria"
    weight = 2

  [[menu.main]]
    name = "Canales TV"
    pre = "<span data-feather='tv'></span>"
    url = "television"
    weight = 3

  [[menu.main]]
    name = "PHP"
    pre = "<span data-feather='code'></span>"
    url = "php"
    weight = 4
